/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: iclartworks (https://sketchfab.com/iclartworks)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-chick-623cc9c755b0417f920037866065efcb
Title: Cute Chick
*/

import * as THREE from 'three'
import React, { useRef ,useEffect} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei/native'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_15: THREE.Mesh
    Object_17: THREE.Mesh
    Object_19: THREE.Mesh
    Object_21: THREE.Mesh
    Object_23: THREE.Mesh
    Object_25: THREE.Mesh
    Object_27: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshPhysicalMaterial
  }
}

const ActionName = 'Animation'

export default function Chick(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF(require('../assets/models/cute_chick.glb')) as GLTFResult
  const { actions } = useAnimations(animations, group)

  useEffect(()=>{
    actions[ActionName]?.play();

  },[])

  return (
    <group ref={group} {...props} dispose={null} scale={2.3}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Cube001_1" position={[0, 0.055, -0.011]} scale={[0.57, 0.739, 0.57]}>
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.Material}
                />
              </group>
              <group
                name="Cube002_2"
                position={[-0.039, 0.57, 0.214]}
                rotation={[-0.707, 0, 0]}
                scale={[0.27, 0.198, 0.234]}>
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials.Material}
                />
              </group>
              <group
                name="Cube003_3"
                position={[-0.133, -0.457, -0.018]}
                rotation={[0, -0.006, 0]}
                scale={[0.191, 0.076, 0.172]}>
                <mesh
                  name="Object_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials['Material.001']}
                />
              </group>
              <group
                name="Cube005_4"
                position={[0.836, 1.211, -0.019]}
                rotation={[-Math.PI, 0, 2.727]}
                scale={[-0.119, -0.071, -0.139]}>
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials['Material.001']}
                />
              </group>
              <group
                name="Cube006_5"
                position={[0.836, 1.211, -0.019]}
                rotation={[3.114, -0.001, -2.705]}
                scale={[-0.119, -0.071, -0.139]}>
                <mesh
                  name="Object_12"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={materials['Material.001']}
                />
              </group>
              <group
                name="Cube007_11"
                position={[0.221, 1.245, 0.012]}
                rotation={[0, 0, 0.223]}
                scale={0.868}>
                <group
                  name="Circle_7"
                  position={[0.659, -0.072, 0.295]}
                  rotation={[-0.02, -0.336, -1.464]}
                  scale={0.121}>
                  <mesh
                    name="Object_15"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_15.geometry}
                    material={materials['Material.003']}
                  />
                </group>
                <group
                  name="Circle001_8"
                  position={[0.558, -0.265, 0.594]}
                  rotation={[-0.027, -0.477, -1.459]}
                  scale={0.18}>
                  <mesh
                    name="Object_17"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_17.geometry}
                    material={materials['Material.004']}
                  />
                </group>
                <group
                  name="Cube_9"
                  position={[-0.228, 0.148, -0.004]}
                  rotation={[0.008, 0.037, -0.223]}
                  scale={1.152}>
                  <mesh
                    name="Object_19"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_19.geometry}
                    material={materials.Material}
                  />
                </group>
              </group>
              <group
                name="Cube008_12"
                position={[0.408, 0.069, -0.333]}
                rotation={[-0.112, 0.436, -0.197]}
                scale={[0.772, 0.999, 0.864]}>
                <mesh
                  name="Object_21"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_21.geometry}
                  material={materials['Material.008']}
                />
              </group>
              <group name="Cube010_14" position={[0, 1.327, 0]} rotation={[0.052, 0.029, 0.214]}>
                <mesh
                  name="Object_23"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_23.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group
                name="Cube011_17"
                position={[0.221, 1.245, 0.012]}
                rotation={[0, 0, 0.223]}
                scale={0.868}>
                <mesh
                  name="Object_25"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_25.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group
                name="Cube012_18"
                position={[-0.028, 0.216, -0.1]}
                rotation={[-0.567, -0.078, 0.024]}
                scale={[0.53, 0.687, 0.53]}>
                <mesh
                  name="Object_27"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_27.geometry}
                  material={materials['Material.008']}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}


